logger:
  levels:
    io.github.opendonationassistant: INFO
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost/postgres?currentSchema=fonts`}
    username: ${JDBC_USER:`postgres`}
    password: ${JDBC_PASSWORD:`postgres`}
    driverClassName: 'org.postgresql.Driver'
    maximumPoolSize: 3
endpoints:
  all:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false
